[project]
name = "fastapi-blog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiosqlite>=0.22.1",
    "bcrypt>=5.0.0",
    "fastapi[standard]>=0.140.0",
    "markdown>=3.10.2",
    "sqlalchemy>=2.0.51",
]

[tool.pyrefly]
project-includes = ["**/*.py"]
project-excludes = [".venv/**", "**/__pycache__/**"]

[dependency-groups]
dev = [
    "djlint>=1.42.3",
    "pyrefly>=1.1.0",
    "ruff>=0.16.0",
]
