"""add now updated at to users

Revision ID: 0641979914ea
Revises: 386e31de133e
Create Date: 2026-08-15 16:08:20.431745

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0641979914ea"
down_revision: str | Sequence[str] | None = "386e31de133e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("now_updated_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "now_updated_at")
    # ### end Alembic commands ###
