"""drop unused likes column from posts

Revision ID: 828492986672
Revises: a92e17a7f012
Create Date: 2026-08-10 07:09:28.981928

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "828492986672"
down_revision: str | Sequence[str] | None = "a92e17a7f012"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "likes")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts",
        sa.Column(
            "likes", sa.INTEGER(), server_default=sa.text("0"), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
