"""add now lines to users

Revision ID: d78ff9ac0bc5
Revises: ff6e72819e00
Create Date: 2026-08-11 15:40:58.262503

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d78ff9ac0bc5"
down_revision: str | Sequence[str] | None = "ff6e72819e00"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("now_building", sa.String(length=120), nullable=True))
    op.add_column("users", sa.Column("now_next", sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "now_next")
    op.drop_column("users", "now_building")
    # ### end Alembic commands ###
